import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name: "tulsi",
    categoryName: "herb",
    image: "/herb/tulsi.jpg",
    price: 400,
    discount: 10,
    discount_amt: 40,
    rating: 3,
  },
  {
    _id: uuid(),
    name: "mascarena",
    categoryName: "palm",
    image: "/palm/mascarena.webp",
    price: 500,
    discount: 10,
    discount_amt: 50,
    rating: 3,
  },
  {
    _id: uuid(),
    name: "syngonium",
    categoryName: "indoor",
    image: "/indoor/syngonium.webp",
    price: 150,
    discount: 10,
    discount_amt: 15,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "spiral bamboo",
    categoryName: "bamboo",
    image: "/bamboo/spiral-bamboo.webp",
    price: 400,
    discount: 10,
    discount_amt: 40,
    rating: 3,
  },
  {
    _id: uuid(),
    name: "mango",
    categoryName: "fruit",
    image: "/fruit/mango.webp",
    price: 400,
    discount: 10,
    discount_amt: 40,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "balsam",
    categoryName: "perennial",
    image: "/perennial/balsam.webp",
    price: 100,
    discount: 10,
    discount_amt: 10,
    rating: 3,
  },
  {
    _id: uuid(),
    name: "petunia",
    categoryName: "perennial",
    image: "/perennial/petunia.webp",
    price: 100,
    discount: 10,
    discount_amt: 10,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "dianthus",
    categoryName: "perennial",
    image: "/perennial/dianthus.webp",
    price: 100,
    discount: 10,
    discount_amt: 10,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "hydrangea",
    categoryName: "perennial",
    image: "/perennial/hydrangea.webp",
    price: 100,
    discount: 10,
    discount_amt: 10,
    rating: 2,
  },
  {
    _id: uuid(),
    name: "marigold",
    categoryName: "perennial",
    image: "/perennial/marigold.webp",
    price: 100,
    discount: 10,
    discount_amt: 10,
    rating: 3,
  },
  {
    _id: uuid(),
    name: "areca",
    categoryName: "palm",
    image: "/palm/areca.webp",
    price: 500,
    discount: 10,
    discount_amt: 50,
    rating: 3,
  },
  {
    _id: uuid(),
    name: "cycas",
    categoryName: "palm",
    image: "/palm/cycas.webp",
    price: 500,
    discount: 10,
    discount_amt: 50,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "raphis",
    categoryName: "palm",
    image: "/palm/raphis.webp",
    price: 500,
    discount: 10,
    discount_amt: 50,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "jade",
    categoryName: "indoor",
    image: "/indoor/jade.webp",
    price: 150,
    discount: 10,
    discount_amt: 15,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "money",
    categoryName: "indoor",
    image: "/indoor/money.webp",
    price: 150,
    discount: 10,
    discount_amt: 15,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "snake",
    categoryName: "indoor",
    image: "/indoor/snake.webp",
    price: 150,
    discount: 10,
    discount_amt: 15,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "spider",
    categoryName: "indoor",
    image: "/indoor/spider.webp",
    price: 150,
    discount: 10,
    discount_amt: 15,
    rating: 3,
  },
  {
    _id: uuid(),
    name: "guava",
    categoryName: "fruit",
    image: "/fruit/guava.webp",
    price: 400,
    discount: 10,
    discount_amt: 40,
    rating: 3,
  },
  {
    _id: uuid(),
    name: "litchi",
    categoryName: "fruit",
    image: "/fruit/litchi.webp",
    price: 400,
    discount: 10,
    discount_amt: 40,
    rating: 4,
  },
  {
    _id: uuid(),
    name: "orange",
    categoryName: "fruit",
    image: "/fruit/orange.webp",
    price: 400,
    discount: 10,
    discount_amt: 40,
    rating: 2,
  },
  {
    _id: uuid(),
    name: "pomegranate",
    categoryName: "fruit",
    image: "/fruit/pomegranate.webp",
    price: 400,
    discount: 10,
    discount_amt: 40,
    rating: 3,
  },
  {
    _id: uuid(),
    name: "lucky bamboo",
    categoryName: "bamboo",
    image: "/bamboo/lucky-bamboo.webp",
    price: 300,
    discount: 15,
    discount_amt: 45,
    rating: 5,
  },
  {
    _id: uuid(),
    name: "coriander",
    categoryName: "herb",
    image: "/herb/coriander.jpg",
    price: 150,
    discount: 10,
    discount_amt: 40,
    rating: 3,
  },
];
